Neos:
  Neos:
    fusion:
      autoInclude:
        NeosRulez.InlineSVG: true
    userInterface:
      translation:
        autoInclude:
          NeosRulez.InlineSVG:
            - 'NodeTypes/*'
            - 'NodeTypes/Content/*'